version: '3'

vars:
  GIT_COMMIT:
    sh: git rev-list -1 HEAD
  BUILD_DATE:
    sh: date --iso-8601=seconds

tasks:
  default:
    cmds:
      - task --list-all
  build:
    cmds:
      - go build -ldflags "-X main.version={{.GIT_COMMIT}} -X main.date={{.BUILD_DATE}}" -o dist/co

  lint:
    deps:
      - vet
      - fmt
      - golangci

  vet:
    cmds:
      - go vet ./...

  fmt:
    cmds:
      - gofmt -l -w -s ./

  golangci:
    cmds:
      - golangci-lint run --modules-download-mode readonly --timeout=10m

  test:
    cmds:
      - go test ./...
